[build]
  base = "dnit-frontend"
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  NEXT_PUBLIC_NATIONAL_IDENTITY_ADDRESS = "0xbB7d162D2445e3e61d232a4f46b8a1Da6a2698E"
  NEXT_PUBLIC_STATIC_TAX_HANDLER_ADDRESS = "0x32dc886F48d02a45D84800DF0b25ACed1636166"
  NEXT_PUBLIC_SEPOLIA_RPC_URL = "https://ethereum-sepolia-rpc.publicnode.com"